name: "Build and Deploy to Cloud Run"

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_ID: "anaregdesign-455601"
  REGION: "asia-northeast1"
  SERVICE: "anaregdesign-web-service"
  DEPLOY_SERVICE_ACCOUNT: "anaregdesign-web-deployer@anaregdesign-455601.iam.gserviceaccount.com"
  WORKLOAD_IDENTITY_PROVIDER: "projects/604272699456/locations/global/workloadIdentityPools/anaregdesign-web-pool/providers/anaregdesign-web-provider"


jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # actions/checkout@v6.0.2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093" # google-github-actions/auth@v3.0.0
        with:
          project_id: "${{ env.PROJECT_ID }}"
          workload_identity_provider: "${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ env.DEPLOY_SERVICE_ACCOUNT }}"
          
      - name: Docker Auth
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/web:${{ github.ref_name }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@2028e2d7d30a78c6910e0632e48dd561b064884d" # google-github-actions/deploy-cloudrun@v3.0.1
        with:
          service: "${{ env.SERVICE }}"
          region: "${{ env.REGION }}"
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/web:${{ github.ref_name }}"
